import type { ModuleConfig } from "../types";

export const modules: ModuleConfig[] = [
  {
    key: "leads",
    title: "Leads y Prospectos",
    endpoint: "leads",
    description: "Registro, edición y seguimiento de prospectos.",
    emoji: "🎯",
    searchFields: ["nombre", "email", "empresa", "telefono"],
    tableFields: ["id", "nombre", "email", "empresa", "telefono", "estado", "score", "fecha_creacion"],
    fields: [
      { name: "nombre", label: "Nombre", type: "text", required: true },
      { name: "email", label: "Correo", type: "email", required: true },
      { name: "empresa", label: "Empresa", type: "text" },
      { name: "telefono", label: "Teléfono", type: "text" },
      {
        name: "estado",
        label: "Estado",
        type: "select",
        options: [
          { label: "Nuevo", value: "nuevo" },
          { label: "Calificado", value: "calificado" },
        ],
      },
      { name: "score", label: "Score", type: "number" },
      { name: "fecha_creacion", label: "Fecha creación", type: "datetime-local", auto: true },
    ],
  },
  {
    key: "usuarios",
    title: "Usuarios",
    endpoint: "usuarios",
    description: "Control de acceso y cuentas del sistema.",
    emoji: "👤",
    searchFields: ["nombre", "email"],
    tableFields: ["id", "nombre", "email", "lead_id", "fecha_creacion"],
    fields: [
      { name: "nombre", label: "Nombre", type: "text", required: true },
      { name: "email", label: "Correo", type: "email", required: true },
      { name: "password", label: "Contraseña", type: "password", required: true },
      { name: "lead_id", label: "Lead relacionado", type: "number" },
      { name: "fecha_creacion", label: "Fecha creación", type: "datetime-local", auto: true },
    ],
  },
  {
    key: "roles",
    title: "Roles",
    endpoint: "roles",
    description: "Definición de perfiles de acceso.",
    emoji: "🛡️",
    searchFields: ["nombre"],
    tableFields: ["id", "nombre"],
    fields: [{ name: "nombre", label: "Nombre", type: "text", required: true }],
  },
  {
    key: "usuario_rol",
    title: "Asignación de Roles",
    endpoint: "usuario_rol",
    description: "Relación entre usuarios y roles.",
    emoji: "🔗",
    tableFields: ["id", "usuario_id", "rol_id"],
    fields: [
      { name: "usuario_id", label: "Usuario ID", type: "number", required: true },
      { name: "rol_id", label: "Rol ID", type: "number", required: true },
    ],
  },
  {
    key: "correos",
    title: "Correos",
    endpoint: "correos",
    description: "Mensajes enviados desde la plataforma.",
    emoji: "✉️",
    tableFields: ["id", "remitente_id", "asunto", "fecha_envio"],
    fields: [
      { name: "remitente_id", label: "Remitente ID", type: "number", required: true },
      { name: "asunto", label: "Asunto", type: "text", required: true },
      { name: "cuerpo", label: "Cuerpo", type: "textarea", required: true },
      { name: "fecha_envio", label: "Fecha envío", type: "datetime-local", auto: true },
    ],
  },
  {
    key: "destinatarios",
    title: "Destinatarios",
    endpoint: "destinatarios",
    description: "TO, CC y BCC de cada correo.",
    emoji: "📨",
    tableFields: ["id", "correo_id", "usuario_id", "tipo", "leido"],
    fields: [
      { name: "correo_id", label: "Correo ID", type: "number", required: true },
      { name: "usuario_id", label: "Usuario ID", type: "number", required: true },
      {
        name: "tipo",
        label: "Tipo",
        type: "select",
        options: [
          { label: "TO", value: "TO" },
          { label: "CC", value: "CC" },
          { label: "BCC", value: "BCC" },
        ],
      },
      { name: "leido", label: "Leído", type: "checkbox" },
    ],
  },
  {
    key: "eventos",
    title: "Eventos",
    endpoint: "eventos",
    description: "Calendario y eventos.",
    emoji: "📅",
    tableFields: ["id", "creador_id", "titulo", "fecha_inicio", "fecha_fin"],
    fields: [
      { name: "creador_id", label: "Creador ID", type: "number", required: true },
      { name: "titulo", label: "Título", type: "text", required: true },
      { name: "descripcion", label: "Descripción", type: "textarea" },
      { name: "fecha_inicio", label: "Fecha inicio", type: "datetime-local", required: true },
      { name: "fecha_fin", label: "Fecha fin", type: "datetime-local", required: true },
    ],
  },
  {
    key: "participantes_evento",
    title: "Participantes de Evento",
    endpoint: "participantes_evento",
    description: "Invitados y estado de respuesta.",
    emoji: "🙋",
    tableFields: ["id", "evento_id", "usuario_id", "estado"],
    fields: [
      { name: "evento_id", label: "Evento ID", type: "number", required: true },
      { name: "usuario_id", label: "Usuario ID", type: "number", required: true },
      {
        name: "estado",
        label: "Estado",
        type: "select",
        options: [
          { label: "Pendiente", value: "pendiente" },
          { label: "Aceptado", value: "aceptado" },
          { label: "Rechazado", value: "rechazado" },
        ],
      },
    ],
  },
  {
    key: "mensajes",
    title: "Mensajería",
    endpoint: "mensajes",
    description: "Chat interno entre usuarios.",
    emoji: "💬",
    tableFields: ["id", "emisor_id", "receptor_id", "fecha"],
    fields: [
      { name: "emisor_id", label: "Emisor ID", type: "number", required: true },
      { name: "receptor_id", label: "Receptor ID", type: "number", required: true },
      { name: "mensaje", label: "Mensaje", type: "textarea", required: true },
      { name: "fecha", label: "Fecha", type: "datetime-local", auto: true },
    ],
  },
  {
    key: "archivos",
    title: "Archivos",
    endpoint: "archivos",
    description: "Documentos y adjuntos del usuario.",
    emoji: "📎",
    tableFields: ["id", "usuario_id", "nombre", "ruta", "fecha_subida"],
    fields: [
      { name: "usuario_id", label: "Usuario ID", type: "number", required: true },
      { name: "nombre", label: "Nombre", type: "text", required: true },
      { name: "ruta", label: "Ruta", type: "text", required: true },
      { name: "fecha_subida", label: "Fecha subida", type: "datetime-local", auto: true },
    ],
  },
  {
    key: "reglas_scoring",
    title: "Reglas de Scoring",
    endpoint: "reglas_scoring",
    description: "Puntajes por tipo de evento.",
    emoji: "📈",
    tableFields: ["id", "tipo_evento", "condicion", "puntos"],
    fields: [
      { name: "tipo_evento", label: "Tipo evento", type: "text", required: true },
      { name: "condicion", label: "Condición", type: "text", required: true },
      { name: "puntos", label: "Puntos", type: "number", required: true },
    ],
  },
  {
    key: "score_historial",
    title: "Historial de Score",
    endpoint: "score_historial",
    description: "Evolución del puntaje de cada lead.",
    emoji: "🧾",
    tableFields: ["id", "lead_id", "puntos", "motivo", "fecha"],
    fields: [
      { name: "lead_id", label: "Lead ID", type: "number", required: true },
      { name: "puntos", label: "Puntos", type: "number", required: true },
      { name: "motivo", label: "Motivo", type: "text", required: true },
      { name: "fecha", label: "Fecha", type: "datetime-local", auto: true },
    ],
  },
  {
    key: "campanas",
    title: "Campañas",
    endpoint: "campañas",
    description: "Marketing por correo y automatizaciones.",
    emoji: "📣",
    tableFields: ["id", "nombre", "tipo", "estado", "fecha_creacion"],
    fields: [
      { name: "nombre", label: "Nombre", type: "text", required: true },
      {
        name: "tipo",
        label: "Tipo",
        type: "select",
        options: [
          { label: "Email", value: "email" },
          { label: "Automatizada", value: "automatizada" },
        ],
      },
      {
        name: "estado",
        label: "Estado",
        type: "select",
        options: [
          { label: "Activa", value: "activa" },
          { label: "Inactiva", value: "inactiva" },
        ],
      },
      { name: "fecha_creacion", label: "Fecha creación", type: "datetime-local", auto: true },
    ],
  },
  {
    key: "emails_enviados",
    title: "Emails Enviados",
    endpoint: "emails_enviados",
    description: "Seguimiento de aperturas y clics.",
    emoji: "📬",
    tableFields: ["id", "lead_id", "campaña_id", "asunto", "abierto", "clic", "fecha_envio"],
    fields: [
      { name: "lead_id", label: "Lead ID", type: "number", required: true },
      { name: "campaña_id", label: "Campaña ID", type: "number", required: true },
      { name: "asunto", label: "Asunto", type: "text", required: true },
      { name: "contenido", label: "Contenido", type: "textarea", required: true },
      { name: "abierto", label: "Abierto", type: "checkbox" },
      { name: "clic", label: "Clic", type: "checkbox" },
      { name: "fecha_envio", label: "Fecha envío", type: "datetime-local", auto: true },
    ],
  },
  {
    key: "formularios",
    title: "Formularios",
    endpoint: "formularios",
    description: "Diseño de formularios web.",
    emoji: "📝",
    tableFields: ["id", "nombre", "fecha_creacion"],
    fields: [
      { name: "nombre", label: "Nombre", type: "text", required: true },
      { name: "descripcion", label: "Descripción", type: "textarea" },
      { name: "fecha_creacion", label: "Fecha creación", type: "datetime-local", auto: true },
    ],
  },
  {
    key: "envio_formularios",
    title: "Envío de Formularios",
    endpoint: "envio_formularios",
    description: "Respuestas capturadas desde formularios.",
    emoji: "📥",
    tableFields: ["id", "formulario_id", "lead_id", "datos", "fecha_envio"],
    fields: [
      { name: "formulario_id", label: "Formulario ID", type: "number", required: true },
      { name: "lead_id", label: "Lead ID", type: "number" },
      { name: "datos", label: "Datos JSON", type: "json", required: true },
      { name: "fecha_envio", label: "Fecha envío", type: "datetime-local", auto: true },
    ],
  },
  {
    key: "reglas_automatizacion",
    title: "Reglas de Automatización",
    endpoint: "reglas_automatizacion",
    description: "Condiciones y acciones automáticas.",
    emoji: "⚙️",
    tableFields: ["id", "nombre", "condicion", "accion", "activa"],
    fields: [
      { name: "nombre", label: "Nombre", type: "text", required: true },
      { name: "condicion", label: "Condición", type: "text", required: true },
      { name: "accion", label: "Acción", type: "text", required: true },
      { name: "activa", label: "Activa", type: "checkbox" },
    ],
  },
  {
    key: "notificaciones",
    title: "Notificaciones",
    endpoint: "notificaciones",
    description: "Alertas automáticas por actividad.",
    emoji: "🔔",
    tableFields: ["id", "lead_id", "mensaje", "atendido", "fecha"],
    fields: [
      { name: "lead_id", label: "Lead ID", type: "number", required: true },
      { name: "mensaje", label: "Mensaje", type: "textarea", required: true },
      { name: "atendido", label: "Atendido", type: "checkbox" },
      { name: "fecha", label: "Fecha", type: "datetime-local", auto: true },
    ],
  },
  {
    key: "notas",
    title: "Notas",
    endpoint: "notas",
    description: "Historial comercial sobre leads.",
    emoji: "🗒️",
    tableFields: ["id", "lead_id", "usuario_id", "contenido", "fecha"],
    fields: [
      { name: "lead_id", label: "Lead ID", type: "number", required: true },
      { name: "usuario_id", label: "Usuario ID", type: "number", required: true },
      { name: "contenido", label: "Contenido", type: "textarea", required: true },
      { name: "fecha", label: "Fecha", type: "datetime-local", auto: true },
    ],
  },
  {
    key: "pruebas",
    title: "Pruebas / Demo",
    endpoint: "pruebas",
    description: "Periodos de prueba asociados a leads.",
    emoji: "🧪",
    tableFields: ["id", "lead_id", "fecha_inicio", "fecha_fin", "estado"],
    fields: [
      { name: "lead_id", label: "Lead ID", type: "number", required: true },
      { name: "fecha_inicio", label: "Fecha inicio", type: "datetime-local", required: true },
      { name: "fecha_fin", label: "Fecha fin", type: "datetime-local", required: true },
      {
        name: "estado",
        label: "Estado",
        type: "select",
        options: [
          { label: "Activa", value: "activa" },
          { label: "Finalizada", value: "finalizada" },
        ],
      },
    ],
  },
];

export const moduleMap = new Map(modules.map((m) => [m.key, m]));